language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
  - truffleruby
matrix:
  allow_failures:
    - rvm: ruby-head
cache: bundler
before_install:
  - gem install bundler -v 1.15.4
  - gem install haml -v 4.0.7
  - gem install haml -v 5.0.4
script:
  - VERBOSE=1 bundle exec rake
